steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - --destination=$LOCATION-docker.pkg.dev/$PROJECT_ID/atomictessellator/socketserver:$SHORT_SHA
    - --destination=$LOCATION-docker.pkg.dev/$PROJECT_ID/atomictessellator/socketserver:$BRANCH_NAME
    - --cache=true
options:
  logging: CLOUD_LOGGING_ONLY



